setopt autocd pushdminus pushdsilent interactivecomments

bindkey -v

# start typing + [Up-Arrow] - fuzzy find history forward
autoload -U up-line-or-beginning-search
zle -N up-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search

# start typing + [Down-Arrow] - fuzzy find history backward
autoload -U down-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

zstyle ':vcs_info:*' disable-patterns "$HOME/.sshfs(|/*)"
zstyle ':completion:*' list-colors 'di=34;01'

typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=''
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=''

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true
typeset -g POWERLEVEL9K_MODE=nerdfont-complete

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir package vcs vi_mode newline prompt_char)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(todo node_version go_version jenv luaenv rust_version anaconda virtualenv gcloud status command_execution_time root_indicator background_jobs battery)

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='—'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=240
POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '
POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' '
POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'

POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_SHOW_PIPESTATUS=false
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=009
POWERLEVEL9K_STATUS_BOLD=true

POWERLEVEL9K_DIR_FOREGROUND=31
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
POWERLEVEL9K_DIR_ANCHOR_BOLD=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique

POWERLEVEL9K_VI_INSERT_MODE_STRING=''
POWERLEVEL9K_VI_COMMAND_MODE_STRING='NORMAL'

POWERLEVEL9K_VCS_CLEAN_FOREGROUND=002
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=208
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=011
POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=009
POWERLEVEL9K_VCS_LOADING_FOREGROUND=$POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND
POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=5

POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="dodgerblue1"

POWERLEVEL9K_NODE_VERSION_SHOW_ON_COMMAND='node|npm|npx|yarn|fnm|now'
POWERLEVEL9K_NODE_VERSION_FOREGROUND=70

POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=0
POWERLEVEL9K_RUST_VERSION_FOREGROUND='darkorange'
POWERLEVEL9K_RUST_VERSION_SHOW_ON_COMMAND='rustc|cargo|rustup|rustdoc|rust-gdb|rust-lldb|rls|clippy-driver|cargo-miri|cargo-fmt|cargo-clippy|rustup-init'

POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=0
POWERLEVEL9K_GO_VERSION_FOREGROUND='051'
POWERLEVEL9K_GO_VERSION_SHOW_ON_COMMAND='go|godoc|gofmt'

# POWERLEVEL9K_PACKAGE_SHOW_ON_COMMAND=$POWERLEVEL9K_NODE_VERSION_SHOW_ON_COMMAND
POWERLEVEL9K_PACKAGE_FOREGROUND='045'

POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud'
POWERLEVEL9K_GCLOUD_FOREGROUND='075'

POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD=10
POWERLEVEL9K_BATTERY_LOW_FOREGROUND=124

POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW=true
POWERLEVEL9K_JENV_SHOW_ON_COMMAND='jenv|java|javac|kotlin|kotlinc|gradle|gw|./gradlew'
POWERLEVEL9K_JENV_FOREGROUND=130

POWERLEVEL9K_LUAENV_PROMPT_ALWAYS_SHOW=true
POWERLEVEL9K_LUAENV_SHOW_ON_COMMAND='lua|luaenv|luarocks'
POWERLEVEL9K_LUAENV_FOREGROUND='021'

POWERLEVEL9K_ANACONDA_FOREGROUND='031'
POWERLEVEL9K_ANACONDA_SHOW_ON_COMMAND='conda|python|python3|python3.8|pip|pip3'

POWERLEVEL9K_VIRTUALENV_FOREGROUND='031'

POWERLEVEL9K_TODO_FOREGROUND='024'
POWERLEVEL9K_TODO_HIDE_ZERO_TOTAL=1
POWERLEVEL9K_TODO_HIDE_ZERO_FILTERED=1

POWERLEVEL9K_INSTANT_PROMPT=quiet
POWERLEVEL9K_TRANSIENT_PROMPT=same-dir

typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
